### ISSUE TITLE
Support for live reload.

### ISSUE THREAD

**Issue by akvdcode** [WorkshopCLI/workshop-cli#10]
It will be nice if you could add support for live reload every time the user saves and after the changes getting deployed.
Using a package like this: https://www.npmjs.com/package/gulp-livereload

**Comment by salexzee** [comment]
Hey @PixMech! This is a great idea. Just a head's up, requests like this are workflow related and not CLI related so it would be in https://github.com/WorkshopCLI/workshop-advanced-gulp or https://github.com/WorkshopCLI/workshop-basic depending on which one you wanted to request this change for... or both.

Full transparency though, at the moment I am busy with other things and this project (meaning Workshop) is at the bottom of my priority list. So odds are I will not be implementing this change any time soon. I'm completely open to you adding this feature though and if you want to submit a pull request I'm sure I can make time for code review/merge/etc.

Closing this out since it's not a change that would be made in this repository. Please open a new issue in one or both of the above linked repositories.

**Comment by akvdcode** [comment]
This is a great project. I felt it was missing the feature for hot reload which is offered by most front end frameworks. Without it I felt this as incomplete.
